apiVersion: v1
data:
    credentials: ENC[AES256_GCM,data:IelZQrHXHgeqdR2eX99L55RuJ8HtyAkPptiZaFb2zSvHtMucZud2y9QtMcRFZIU4khANNUiebfMO6qezkrztHv1HRXhhsOx4HJiNwgTAPX1UOvFhiEKPzJx+3yVZ5KCyD9B4mdbiPYU0ahZqSA2pLhT4/OvICZ8n6ZhkUlXtr95E9Bv9c2UIEn5IgwtIR79AZ1a+jMU03ZTCC6w/3OfsCLhglN6okF5IcG+BsLeDJ1RrS91Qsuz1+mBHy1zW4cYsfR34QOlgcRs4XJXc2CgV64wpzHCr4yYr,iv:rtRyg0DPXDzForiyobN8Ury5WhZoV2Vk0sZLrfZGo1Q=,tag:80j49VrJ0Rrx9QQpVmKp0A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kkpamr3neu7m38q0kn5xvextgrg5s6qwx8aglhal4sss4exelfrsdp26tj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKN2N0UHRVK2RVVGZ3MGN4
            MERYMjRxaTExRmI5ZTdJTkNST1NMMGt6TGlJCm1tMm1DbWxZMllTMndML1FQZ3RS
            dVlIaEd5TlpFU2d2WWxCbTZiSE5KUkkKLS0tIEhodzBFemhlS1ZaVmtvUWdMcitI
            TUdrTEZ1U0ZQNmxlU0RoV1FIaWlVM00Klv+8ejwWXwyPgP1DSUyjyOKcbCHJevd6
            /XnuuzwuH5rjoQFmwWKBm/PRYxXhEnusVUoJflrEmBJwdcGTXqMFjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-27T05:12:59Z"
    mac: ENC[AES256_GCM,data:Own9DHIxbeoCeA+h0KZuCKd5THRKtIM3Wq2VoCjT7DgLDjZka8FfPVKm9XnlCBkwm2G7R9/k1z286swc+eQjFGEDwiyxpnykTMwvGGfKlI9oPobsMumtPTKwfFe/+oxlg/+ZQ0JjhBd/6is2OrpWKuutA884Fe8ouQeTK3gpmmI=,iv:EfeqEJw/992f9xuQkz+1wFHfE6j5PFljBIuHHMvZSH0=,tag:1G7+wGYb/ToC7p4+e0AGVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
