apiVersion: v1
kind: Service
metadata:
  name: linkding-svc
  namespace: linkding
spec:
  type: NodePort
  selector: 
    app: linkding
  ports:
    - NodePort: 8080
      port: 80
      targetPort: 9090